### PR TITLE
[CurrentPlaceDetailOnMap] Adjust permission request flow and fix some null issues

### PR DESCRIPTION
**Pull request by Kuan-Hsien**
1. Add some check for instance of GoogleMap and result of tasks to prevent NullPointerException
2. Always check permission before use location related functions to prevent LastLocation from null

### CODE REVIEW

**Comment by Kuan-Hsien** [comment]
@googlebot I signed it!

**Comment by amuramoto** [comment]
@wangela ping! Can you take a look at this since it's related to Places?

**Comment by amuramoto** [comment]
@Kuan-Hsien  Thanks for the PR!

**Comment by wangela** [comment]
Hey @Kuan-Hsien, thanks for the PR. This was merged into our v3-beta branch which is just for the [Maps SDK for Android v3 Beta](https://developers.google.com/maps/documentation/android-sdk/v3-client-migration). Would you like to submit a PR to make your contributions visible in master?

**Pull request merged**
